autopep8==1.6.0
certifi==2020.6.20
joblib==1.1.0
numpy==1.22.0
pandas==1.3.5
pip==21.2.4
pycodestyle==2.8.0
python-dateutil==2.8.2
pytz==2021.3
scikit-learn==1.0.2
scipy==1.7.3
setuptools==58.0.4
six==1.16.0
threadpoolctl==2.2.0
toml==0.10.2
wheel==0.37.1
wincertstore==0.2
